{% set name = "argocd-cli" %}
{% set version = "2.14.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/argoproj/argo-cd/archive/v{{ version }}.tar.gz
  sha256: e81aa0f5e48f207f164fbd499a15b2bc4ed7400be1d5bbb4d10fa035d4fd192c

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - ripgrep
  commands:
    - argocd --help
    - argocd version | rg {{ version }}

about:
  summary: Declarative Continuous Deployment for Kubernetes
  home: https://github.com/argoproj/argo-cd
  license: Apache-2.0
  license_file:
    - LICENSE
    - thirdparty/

extra:
  recipe-maintainers:
    - dhirschfeld
