{% set name = "argocd-cli" %}
{% set version = "3.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/argoproj/argo-cd/archive/v{{ version }}.tar.gz
  sha256: f5e94de7c87bc57dbe4154f35146e5e19f4deb8c1534b8011999eb19bce69640

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - ripgrep
  commands:
    - argocd --help
    - argocd version --client
    - argocd version --client | rg -F '{{ version }}'

about:
  summary: Declarative Continuous Deployment for Kubernetes
  home: https://github.com/argoproj/argo-cd
  license: Apache-2.0
  license_file:
    - LICENSE
    - thirdparty/

extra:
  recipe-maintainers:
    - dhirschfeld
