{% set name = "argocd-cli" %}
{% set version = "3.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/argoproj/argo-cd/archive/v{{ version }}.tar.gz
  sha256: 3794d48b500330ebfaf06af6e4d45a9c9f2c8eb9011b02c205ef8c9c9f4a86d1

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - ripgrep
  commands:
    - argocd --help
    - argocd version --client
    - argocd version --client | rg -F '{{ version }}'

about:
  summary: Declarative Continuous Deployment for Kubernetes
  home: https://github.com/argoproj/argo-cd
  license: Apache-2.0
  license_file:
    - LICENSE
    - thirdparty/

extra:
  recipe-maintainers:
    - dhirschfeld
