{% set name = "argocd-cli" %}
{% set version = "2.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/argoproj/argo-cd/archive/v{{ version }}.tar.gz
  sha256: 711fd27a1a6b68b4eb6fd8c90743a22cd2defeef9638b0be74584a86f6663cb6

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - ripgrep
  commands:
    - argocd --help
    - argocd version | rg {{ version }}

about:
  summary: Declarative Continuous Deployment for Kubernetes
  home: https://github.com/argoproj/argo-cd
  license: Apache-2.0
  license_file:
    - LICENSE
    - thirdparty/

extra:
  recipe-maintainers:
    - dhirschfeld
