{% set name = "argocd-cli" %}
{% set version = "2.12.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/argoproj/argo-cd/archive/v{{ version }}.tar.gz
  sha256: 5fbf4455c053412904c67b2a25c44f92bad41617c8b2c4b94faf56f2c7726552

build:
  skip: true  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - ripgrep
  commands:
    - argocd --help
    - argocd version | rg {{ version }}

about:
  summary: Declarative Continuous Deployment for Kubernetes
  home: https://github.com/argoproj/argo-cd
  license: Apache-2.0
  license_file:
    - LICENSE
    - thirdparty/

extra:
  recipe-maintainers:
    - dhirschfeld
